/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import JDBC.Conexion;
import Metodos.MetodosCalendarios;
import WebCam.Capturadora;
import com.sun.awt.AWTUtilities;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import JDBC.MetodosBaseDeDatos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author anthony
 */
public class FrameMarcador extends javax.swing.JFrame {

    int posX, posY;
    ButtonGroup bg = new ButtonGroup();
    /**
     * Creates new form FrameMarcador
     */
    public FrameMarcador() {
        setUndecorated(true);  
        initComponents(); 
        setLocationRelativeTo(null);
        setResizable(false);
        botonRadio();
        txtCajaCodigo.setEditable(false);
        Conexion d = new Conexion();
        d.Conec();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void botonRadio(){
        bg.add(rbEntrada);
        bg.add(rbSalida);
    }
    
    public boolean contarCodigo() {
        boolean verificador = false;
        if (txtCajaCodigo.getText().length() < 4) 
            return verificador = true;
        return verificador;
    }
    
    public void insertarNumero(String num){
        if(contarCodigo() == true)
            txtCajaCodigo.setText(txtCajaCodigo.getText()+num);
        else
            JOptionPane.showMessageDialog(null, "Codigo Lleno", "Error",JOptionPane.ERROR_MESSAGE);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbEntrada = new javax.swing.JRadioButton();
        txtCajaCodigo = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        btnMarcar = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        rbSalida = new javax.swing.JRadioButton();
        btn1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnDepartamento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbEntrada.setText("Entrada");
        rbEntrada.setContentAreaFilled(false);
        rbEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(rbEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, 30));

        txtCajaCodigo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtCajaCodigo.setForeground(new java.awt.Color(5, 168, 203));
        txtCajaCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCajaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCajaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 250, 45));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TresBig.png"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setFocusPainted(false);
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TresSmall.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 64, 64));

        btnMarcar.setText("Marcar");
        btnMarcar.setBorderPainted(false);
        btnMarcar.setContentAreaFilled(false);
        btnMarcar.setFocusPainted(false);
        btnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 90, 50));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarCeleste.png"))); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setFocusPainted(false);
        jButton19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarGris.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 5, 70, 70));

        btnClear.setText("Limpiar");
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, 50));

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CeroBig.png"))); // NOI18N
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setFocusPainted(false);
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CeroSmall.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 64, 64));

        rbSalida.setText("Salida");
        rbSalida.setContentAreaFilled(false);
        rbSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(rbSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 70, 30));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UnoBig.png"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setFocusPainted(false);
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UnoSmall.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 64, 64));

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SieteBig.png"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setFocusPainted(false);
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SieteSmall.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 64, 64));

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CincoBig.png"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setFocusPainted(false);
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CincoSmall.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 64, 64));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinimizarCeleste.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MinimizarGris.png.png"))); // NOI18N
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 5, 70, 70));

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroUsarioBig.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.setFocusPainted(false);
        btnRegistro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroUsuarioSmall.png"))); // NOI18N
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 64, 64));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DosBig.png"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setFocusPainted(false);
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DosSmall.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 64, 64));

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OchoBig.png"))); // NOI18N
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setFocusPainted(false);
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OchoSmall.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 64, 64));

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SeisBig.png"))); // NOI18N
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setFocusPainted(false);
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SeisSmall.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 64, 64));

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NueveBig.png"))); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setFocusPainted(false);
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NueveSmall.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 64, 64));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuatroBig.png"))); // NOI18N
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setFocusPainted(false);
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuatroSmall.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 64, 64));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportePdfBig.png"))); // NOI18N
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setFocusPainted(false);
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReportePdfSmall.png"))); // NOI18N
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 64, 64));

        btnDepartamento.setText("Departamento");
        btnDepartamento.setBorderPainted(false);
        btnDepartamento.setContentAreaFilled(false);
        btnDepartamento.setFocusPainted(false);
        btnDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 120, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPrincipal.png"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCajaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaCodigoActionPerformed
        
    }//GEN-LAST:event_txtCajaCodigoActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        insertarNumero("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        insertarNumero("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        insertarNumero("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        insertarNumero("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        insertarNumero("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        insertarNumero("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        insertarNumero("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        insertarNumero("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        insertarNumero("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        insertarNumero("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "¿Desea borrar el codigo?", "¿Esta Seguro?",JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
        if(opc == JOptionPane.YES_OPTION)
            txtCajaCodigo.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void rbSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSalidaActionPerformed

    private void rbEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEntradaActionPerformed

    private void btnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarActionPerformed
        MetodosBaseDeDatos met = new MetodosBaseDeDatos();
        if(verificarRadio() == true){
            if(met.existe("tblusuario", "codigo", txtCajaCodigo.getText(), "Usuario no existe" ) == true){
                if(rbSalida.isSelected()){
                    if(verificarEntrada() == true){
                        if(rbSalida.isSelected()){
                            Capturadora c = new Capturadora(txtCajaCodigo.getText(), MetodosCalendarios.Fecha(), MetodosCalendarios.hora(),"S");
                            c.setVisible(true);
                        }
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Usuario no ha marcado Entrada");
                }
                else{
                    Capturadora c = new Capturadora(txtCajaCodigo.getText(), MetodosCalendarios.Fecha(), MetodosCalendarios.hora(), "E");
                    c.setVisible(true);
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione tipo de Marcaje");
    }//GEN-LAST:event_btnMarcarActionPerformed
    
    //Este metodo verifica si el usuario ah seleccionado algun radioButton, en caso de no haberlo hecho no podra continuar
    private boolean verificarRadio(){
        try{
            if(rbEntrada.isSelected() || rbSalida.isSelected())
                return true;
            else
                return false;
        }
        catch(NullPointerException e){    
            return false;
        }
    }
    
    //Este metodo nos especifíca si el usuario ya ha marcado la entrada, en caso de no haberlo hecho, no podra marcar la salida
    private boolean verificarEntrada(){
        Conexion cn = new Conexion();
        Connection link = cn.Conec();
        try{
            PreparedStatement usu = link.prepareStatement("SELECT * FROM tblregistro WHERE usuario = '"+txtCajaCodigo.getText()+"' && TIPO_IN_OUT = '"+"E"+"'");
            ResultSet rs = usu.executeQuery();
            if(rs.next())
                return true;
            else
                return false;
        }
        catch(SQLException e){
            e.printStackTrace();
            return false;
        }
    }
    
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        FrameFormulario f = new FrameFormulario();
        AWTUtilities.setWindowOpaque(f, false);
        f.setVisible(true);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrameReportes f = new FrameReportes();
        AWTUtilities.setWindowOpaque(f, false);
        f.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        int xp = evt.getXOnScreen() - posX;
        int yp = evt.getYOnScreen() - posY;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void btnDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentoActionPerformed
        FrameDepartamento f = new FrameDepartamento();
        AWTUtilities.setWindowOpaque(f, false);
        f.setVisible(true);
    }//GEN-LAST:event_btnDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMarcador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDepartamento;
    private javax.swing.JButton btnMarcar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbSalida;
    private javax.swing.JTextField txtCajaCodigo;
    // End of variables declaration//GEN-END:variables
}
